"""add flock bodyweight models

Revision ID: 3463bd0c4ada
Revises: b68758f5b4ec
Create Date: 2026-05-17 13:49:14.677977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3463bd0c4ada'
down_revision = 'b68758f5b4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broiler_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('water_to_feed_ratio', sa.Float(), nullable=True),
    sa.Column('live_weight', sa.Float(), nullable=True),
    sa.Column('daily_gain', sa.Float(), nullable=True),
    sa.Column('avg_daily_gain', sa.Float(), nullable=True),
    sa.Column('feed_consumption', sa.Float(), nullable=True),
    sa.Column('cum_feed_consumption', sa.Float(), nullable=True),
    sa.Column('fcr', sa.Float(), nullable=True),
    sa.Column('econ_fcr', sa.Float(), nullable=True),
    sa.Column('daily_depletion_rate', sa.Float(), nullable=True),
    sa.Column('cum_depletion_rate', sa.Float(), nullable=True),
    sa.Column('pef', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broiler_standard'))
    )
    op.create_table('notification_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_rule'))
    )
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_history'))
    )
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_history_user_id'), ['user_id'], unique=False)

    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_push_subscription_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscription'))
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_activity_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_log'))
    )
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('flock_grading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('age_week', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('average_weight', sa.Float(), nullable=True),
    sa.Column('uniformity', sa.Float(), nullable=True),
    sa.Column('lowest_weight', sa.Float(), nullable=True),
    sa.Column('highest_weight', sa.Float(), nullable=True),
    sa.Column('grading_bins', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_flock_grading_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flock_grading'))
    )
    with op.batch_alter_table('flock_grading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flock_grading_age_week'), ['age_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_flock_grading_house_id'), ['house_id'], unique=False)

    op.create_table('flock_bodyweight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('age_week', sa.Integer(), nullable=True),
    sa.Column('body_weight_male', sa.Float(), nullable=True),
    sa.Column('body_weight_female', sa.Float(), nullable=True),
    sa.Column('uniformity_male', sa.Float(), nullable=True),
    sa.Column('uniformity_female', sa.Float(), nullable=True),
    sa.Column('standard_bw_male', sa.Integer(), nullable=True),
    sa.Column('standard_bw_female', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_flock_bodyweight_flock_id_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flock_bodyweight'))
    )
    with op.batch_alter_table('flock_bodyweight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flock_bodyweight_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_flock_bodyweight_flock_id'), ['flock_id'], unique=False)

    op.create_table('hatchery_egg_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('grading_timestamp', sa.DateTime(), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('farm_declared_qty', sa.Integer(), nullable=False),
    sa.Column('actual_received_qty', sa.Integer(), nullable=False),
    sa.Column('jumbo_cull', sa.Integer(), nullable=False),
    sa.Column('small_cull', sa.Integer(), nullable=False),
    sa.Column('abnormal_cull', sa.Integer(), nullable=False),
    sa.Column('crack_cull', sa.Integer(), nullable=False),
    sa.Column('settable_eggs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_hatchery_egg_receipt_farm_id_farm')),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_hatchery_egg_receipt_flock_id_flock')),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_hatchery_egg_receipt_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hatchery_egg_receipt'))
    )
    with op.batch_alter_table('hatchery_egg_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hatchery_egg_receipt_arrival_date'), ['arrival_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchery_egg_receipt_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchery_egg_receipt_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchery_egg_receipt_house_id'), ['house_id'], unique=False)

    op.create_table('house_flock_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_house_flock_mapping_farm_id_farm')),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_house_flock_mapping_flock_id_flock')),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_house_flock_mapping_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_house_flock_mapping'))
    )
    with op.batch_alter_table('house_flock_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_house_flock_mapping_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_house_flock_mapping_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_house_flock_mapping_house_id'), ['house_id'], unique=False)

    op.create_table('studio_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('chart_identifier', sa.String(length=50), nullable=False),
    sa.Column('anchor_data_x', sa.String(length=50), nullable=False),
    sa.Column('anchor_data_y', sa.Float(), nullable=False),
    sa.Column('fabric_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_studio_annotation_flock_id_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_annotation'))
    )
    with op.batch_alter_table('studio_annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_annotation_chart_identifier'), ['chart_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_annotation_flock_id'), ['flock_id'], unique=False)

    op.create_table('flock_bodyweight_partition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodyweight_id', sa.Integer(), nullable=False),
    sa.Column('partition_name', sa.String(length=10), nullable=False),
    sa.Column('body_weight', sa.Float(), nullable=True),
    sa.Column('uniformity', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['bodyweight_id'], ['flock_bodyweight.id'], name=op.f('fk_flock_bodyweight_partition_bodyweight_id_flock_bodyweight')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flock_bodyweight_partition'))
    )
    with op.batch_alter_table('flock_bodyweight_partition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flock_bodyweight_partition_bodyweight_id'), ['bodyweight_id'], unique=False)

    with op.batch_alter_table('broiler_daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cull_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broiler_daily_log', schema=None) as batch_op:
        batch_op.drop_column('cull_count')

    with op.batch_alter_table('flock_bodyweight_partition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_bodyweight_partition_bodyweight_id'))

    op.drop_table('flock_bodyweight_partition')
    with op.batch_alter_table('studio_annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_annotation_flock_id'))
        batch_op.drop_index(batch_op.f('ix_studio_annotation_chart_identifier'))

    op.drop_table('studio_annotation')
    with op.batch_alter_table('house_flock_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_house_flock_mapping_house_id'))
        batch_op.drop_index(batch_op.f('ix_house_flock_mapping_flock_id'))
        batch_op.drop_index(batch_op.f('ix_house_flock_mapping_farm_id'))

    op.drop_table('house_flock_mapping')
    with op.batch_alter_table('hatchery_egg_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hatchery_egg_receipt_house_id'))
        batch_op.drop_index(batch_op.f('ix_hatchery_egg_receipt_flock_id'))
        batch_op.drop_index(batch_op.f('ix_hatchery_egg_receipt_farm_id'))
        batch_op.drop_index(batch_op.f('ix_hatchery_egg_receipt_arrival_date'))

    op.drop_table('hatchery_egg_receipt')
    with op.batch_alter_table('flock_bodyweight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_bodyweight_flock_id'))
        batch_op.drop_index(batch_op.f('ix_flock_bodyweight_date'))

    op.drop_table('flock_bodyweight')
    with op.batch_alter_table('flock_grading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_grading_house_id'))
        batch_op.drop_index(batch_op.f('ix_flock_grading_age_week'))

    op.drop_table('flock_grading')
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_log_timestamp'))

    op.drop_table('user_activity_log')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_history_created_at'))

    op.drop_table('notification_history')
    op.drop_table('notification_rule')
    op.drop_table('broiler_standard')
    # ### end Alembic commands ###
