"""add flock bodyweight models

Revision ID: 3463bd0c4ada
Revises: b68758f5b4ec
Create Date: 2026-05-17 13:49:14.677977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3463bd0c4ada'
down_revision = 'b68758f5b4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(bind)
    
    if not inspector.has_table('flock_bodyweight'):
        op.create_table('flock_bodyweight',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('flock_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('age_week', sa.Integer(), nullable=True),
        sa.Column('body_weight_male', sa.Float(), nullable=True),
        sa.Column('body_weight_female', sa.Float(), nullable=True),
        sa.Column('uniformity_male', sa.Float(), nullable=True),
        sa.Column('uniformity_female', sa.Float(), nullable=True),
        sa.Column('standard_bw_male', sa.Integer(), nullable=True),
        sa.Column('standard_bw_female', sa.Integer(), nullable=True),
        sa.Column('version', sa.Integer(), server_default='1', nullable=False),
        sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_flock_bodyweight_flock_id_flock')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_flock_bodyweight'))
        )
        with op.batch_alter_table('flock_bodyweight', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_flock_bodyweight_date'), ['date'], unique=False)
            batch_op.create_index(batch_op.f('ix_flock_bodyweight_flock_id'), ['flock_id'], unique=False)

    if not inspector.has_table('flock_bodyweight_partition'):
        op.create_table('flock_bodyweight_partition',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bodyweight_id', sa.Integer(), nullable=False),
        sa.Column('partition_name', sa.String(length=10), nullable=False),
        sa.Column('body_weight', sa.Float(), nullable=True),
        sa.Column('uniformity', sa.Float(), nullable=True),
        sa.Column('version', sa.Integer(), server_default='1', nullable=False),
        sa.ForeignKeyConstraint(['bodyweight_id'], ['flock_bodyweight.id'], name=op.f('fk_flock_bodyweight_partition_bodyweight_id_flock_bodyweight')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_flock_bodyweight_partition'))
        )
        with op.batch_alter_table('flock_bodyweight_partition', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_flock_bodyweight_partition_bodyweight_id'), ['bodyweight_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flock_bodyweight_partition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_bodyweight_partition_bodyweight_id'))

    op.drop_table('flock_bodyweight_partition')
    with op.batch_alter_table('flock_bodyweight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flock_bodyweight_flock_id'))
        batch_op.drop_index(batch_op.f('ix_flock_bodyweight_date'))

    op.drop_table('flock_bodyweight')
    # ### end Alembic commands ###
