"""add department to farm

Revision ID: 5624481a4593
Revises: 5bcde1cabaa2
Create Date: 2026-05-30 02:47:49.976808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5624481a4593'
down_revision = '5bcde1cabaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), server_default='Breeder', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_column('department')
    # ### end Alembic commands ###
