"""Generate missing multi-farm relationships

Revision ID: b68758f5b4ec
Revises: c5517872a7f7
Create Date: 2026-05-12 05:37:41.939021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68758f5b4ec'
down_revision = 'c5517872a7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_configuration')
    op.drop_table('overview_configuration')
    with op.batch_alter_table('chart_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_note_chart_identifier'))
        batch_op.drop_index(batch_op.f('ix_chart_note_flock_id'))

    op.drop_table('chart_note')
    op.drop_table('floating_note')
    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.create_index(batch_op.f('ix_clinical_note_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('males_in_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('males_out_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('females_in_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('females_out_flock', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_daily_entry_submitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('selection_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spiking', sa.Boolean(), nullable=True))
        batch_op.alter_column('body_weight_male',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('body_weight_female',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uniformity_male',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('uniformity_female',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.create_index(batch_op.f('ix_daily_log_feed_code_female_id'), ['feed_code_female_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_feed_code_male_id'), ['feed_code_male_id'], unique=False)
        batch_op.drop_column('feed_male')
        batch_op.drop_column('feed_female')

    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_photo_note_id'), ['note_id'], unique=False)

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('feed_code', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_flock_batch_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_flock_flock_id'), ['flock_id'])
        batch_op.drop_column('production_start_date')

    with op.batch_alter_table('hatchability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hatchability_candling_date'), ['candling_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_hatching_date'), ['hatching_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hatchability_setting_date'), ['setting_date'], unique=False)

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_house_farm_id'), ['farm_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_house_farm_id_farm'), 'farm', ['farm_id'], ['id'])
        batch_op.drop_column('version')

    with op.batch_alter_table('imported_weekly_benchmark', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('batch_number')
        batch_op.drop_column('expiry_date')

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_inventory_transaction_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transaction_transaction_date'), ['transaction_date'], unique=False)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('partition_weight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partition_weight_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('sampling_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sampling_event_age_week'), ['age_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_event_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_event_status'), ['status'], unique=False)

    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('ui_element', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.drop_column('version')

    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccine_actual_date'), ['actual_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_est_date'), ['est_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_inventory_item_id'), ['inventory_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_vaccine_flock_id'))
        batch_op.drop_index(batch_op.f('ix_vaccine_est_date'))
        batch_op.drop_index(batch_op.f('ix_vaccine_actual_date'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('farm_id')

    with op.batch_alter_table('ui_element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('sampling_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sampling_event_status'))
        batch_op.drop_index(batch_op.f('ix_sampling_event_flock_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_event_age_week'))

    with op.batch_alter_table('partition_weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partition_weight_log_id'))

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_start_date'))
        batch_op.drop_index(batch_op.f('ix_medication_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_medication_flock_id'))
        batch_op.drop_index(batch_op.f('ix_medication_end_date'))

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_transaction_inventory_item_id'))
        batch_op.drop_column('version')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('batch_number')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('batch_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('imported_weekly_benchmark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_house_farm_id_farm'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_house_farm_id'))
        batch_op.drop_column('farm_id')

    with op.batch_alter_table('hatchability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hatchability_setting_date'))
        batch_op.drop_index(batch_op.f('ix_hatchability_hatching_date'))
        batch_op.drop_index(batch_op.f('ix_hatchability_flock_id'))
        batch_op.drop_index(batch_op.f('ix_hatchability_candling_date'))

    with op.batch_alter_table('flock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_start_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_flock_flock_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_flock_batch_id'), ['flock_id'])
        batch_op.alter_column('farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('feed_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('daily_log_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_photo_note_id'))

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_female', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('feed_male', sa.FLOAT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_male_id'))
        batch_op.drop_index(batch_op.f('ix_daily_log_feed_code_female_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('uniformity_female',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('uniformity_male',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('body_weight_female',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('body_weight_male',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('spiking')
        batch_op.drop_column('selection_done')
        batch_op.drop_column('remarks')
        batch_op.drop_column('is_daily_entry_submitted')
        batch_op.drop_column('females_out_flock')
        batch_op.drop_column('females_in_flock')
        batch_op.drop_column('males_out_flock')
        batch_op.drop_column('males_in_flock')

    with op.batch_alter_table('clinical_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_note_log_id'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    op.create_table('floating_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('chart_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('x_value', sa.VARCHAR(length=50), nullable=False),
    sa.Column('y_value', sa.FLOAT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_floating_note_flock_id_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floating_note'))
    )
    op.create_table('chart_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flock_id', sa.INTEGER(), nullable=False),
    sa.Column('chart_identifier', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('pos_x', sa.FLOAT(), nullable=False),
    sa.Column('pos_y', sa.FLOAT(), nullable=False),
    sa.Column('width', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], name=op.f('fk_chart_note_flock_id_flock')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_note'))
    )
    with op.batch_alter_table('chart_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_note_flock_id'), ['flock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_note_chart_identifier'), ['chart_identifier'], unique=False)

    op.create_table('overview_configuration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_id', sa.INTEGER(), nullable=False),
    sa.Column('visible_metrics_json', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_overview_configuration_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overview_configuration')),
    sa.UniqueConstraint('house_id', name=op.f('uq_overview_configuration_house_id'))
    )
    op.create_table('chart_configuration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('chart_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('config_json', sa.TEXT(), nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name=op.f('fk_chart_configuration_house_id_house')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_configuration'))
    )
    # ### end Alembic commands ###
